// Function declarations for thread functions
#ifndef RECRUITING_SW_TELEMETRY_PROJECT_2_THREAD_FUNCTIONS_H
#define RECRUITING_SW_TELEMETRY_PROJECT_2_THREAD_FUNCTIONS_H

void idleThread();

void runThread();

#endif //RECRUITING_SW_TELEMETRY_PROJECT_2_THREAD_FUNCTIONS_H
